server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdb?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: stella@6767

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true 